[package]
name = "Hermes"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_macros = { path = "./derive_macros" }
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.7", features = ["fs"] }
serde = { version = "1", features = ["derive"] }
sqlx = { version = "0.8", features = ["postgres", "runtime-tokio", "uuid"] }
uuid = { version = "1", features = ["v4", "serde"] }
axum = { version = "0.8.9", features = ["macros"] }
axum-extra = { version = "0.12.6", features = ["typed-header"] }
jsonwebtoken = { version = "10", default-features = false, features = ["aws_lc_rs"] }
dotenvy = "0.15.7"
time = "0.3.54"
serde_json = "1.0.151"