[package]
name = "Hermes"
version = "0.1.0"
edition = "2024"

[toolchain]
channel = "nightly"

[dependencies]
derive_macros = { path = "./derive_macros" }
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.7", features = ["fs", "cors"] }
serde = { version = "1", features = ["derive"] }
sqlx = { version = "0.9", features = ["postgres", "sqlite", "runtime-tokio", "uuid"] }
uuid = { version = "1", features = ["v4", "serde"] }
axum = { version = "0.8.9", features = ["macros", "multipart"] }
axum-extra = { version = "0.12.6", features = ["typed-header"] }
jsonwebtoken = { version = "10", default-features = false, features = ["aws_lc_rs"] }
fred = "10.1.0"
dotenvy = "0.15.7"
sha2 = "0.11.0"
hex = "0.4.3"
infer = "0.22.0"
time = "0.3.54"
serde_json = "1.0.151"