CREATE TABLE "users" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "username" varchar NOT NULL,
  "password" varchar NOT NULL
);

CREATE TABLE "groups" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "name" varchar NOT NULL,
  "is_dm" bool NOT NULL
);

CREATE TABLE "group_members" (
  "group_id" uuid NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
  "member_id"  uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  PRIMARY KEY (group_id, member_id)
);

CREATE TABLE "messages" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "message" varchar,
  "files" bytea[],
  "group_id" uuid NOT NULL,
  "user_id" uuid
);

ALTER TABLE "messages" ADD CONSTRAINT "user_msg" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "messages" ADD CONSTRAINT "group_msg" FOREIGN KEY ("group_id") REFERENCES "groups" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

CREATE OR REPLACE FUNCTION enforce_dm() RETURNS trigger AS $$
DECLARE
    is_dm_group boolean;
    member_count int;
BEGIN
    SELECT is_dm INTO is_dm_group FROM groups WHERE id = NEW.group_id;

    IF is_dm_group THEN
        SELECT count(*) INTO member_count FROM group_members
        WHERE group_id = NEW.group_id;

        IF member_count >= 2 THEN
            RAISE EXCEPTION 'DM groups cannot have more than 2 members';
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_check_dm_compliance
BEFORE INSERT ON group_members
FOR EACH ROW EXECUTE FUNCTION enforce_dm();