CREATE TABLE "users" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "username" varchar NOT NULL,
  "password" varchar NOT NULL
);

CREATE TABLE "groups" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "member_id" uuid NOT NULL
);

CREATE TABLE "messages" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "message" varchar,
  "files" bytea[],
  "user_id" uuid,
  "group_id" uuid
);

ALTER TABLE "groups" ADD CONSTRAINT "group_member" FOREIGN KEY ("member_id") REFERENCES "users" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "messages" ADD CONSTRAINT "user_msg" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "messages" ADD CONSTRAINT "groub_msg" FOREIGN KEY ("group_id") REFERENCES "groups" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
