
CREATE TYPE relation_t AS ENUM ('Friends', 'Pending', 'Blocked');
CREATE TYPE privilege_t AS ENUM ('Consumer', 'Proprietor');
CREATE TYPE rank_t AS ENUM ('User', 'Admin', 'Owner');

CREATE TABLE "users" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "nickname" text NOT NULL,
  "prv" privilege_t NOT NULL,
  "username" text NOT NULL UNIQUE,
  "password" text NOT NULL,
  "pfp" uuid
);

CREATE TABLE "relations" (
  "relating_user" uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  "related_user" uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  "state" relation_t NOT NULL,
  PRIMARY KEY (relating_user, related_user),
  CONSTRAINT friend_equality CHECK (relating_user != related_user)
);

CREATE TABLE "groups" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "is_dm" bool NOT NULL
);

CREATE TABLE "guilds" (
  "group_id" uuid PRIMARY KEY REFERENCES groups(id) ON DELETE CASCADE,
  "name" text NOT NULL,
  "gp" uuid REFERENCES objects(id) ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE
);

CREATE TABLE "dms" (
  "group_id" uuid PRIMARY KEY REFERENCES groups(id) ON DELETE CASCADE,
  "user_a" uuid  REFERENCES users(id) ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE,
  "user_b" uuid  REFERENCES users(id) ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE,
  UNIQUE (user_a, user_b)
);

CREATE TABLE "guild_invites" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "group_id" uuid NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
  "user_id" uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  "rank" rank_t NOT NULL
);

CREATE TABLE "dm_invites" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "group_id" uuid NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
  "user_id" uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE "guild_members" (
  "group_id" uuid NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
  "member_id" uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  "rank" rank_t NOT NULL,
  PRIMARY KEY (group_id, member_id)
);

CREATE TABLE "messages" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "message" text,
  "group_id" uuid NOT NULL,
  "user_id" uuid
);

CREATE TABLE "objects" (
  "id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  "hash" char(64) NOT NULL UNIQUE,
  "rel_path" text NOT NULL UNIQUE,
  "mime_type" text NOT NULL,
  "size_bytes" bigint NOT NULL,
  "creation_timestamp" bigint NOT NULL
);

CREATE TABLE "message_objects" (
  "message_id" integer NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
  "object_id" uuid NOT NULL REFERENCES objects(id) ON DELETE CASCADE,
  PRIMARY KEY (message_id, object_id)
);

ALTER TABLE "messages" ADD CONSTRAINT "user_msg" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "messages" ADD CONSTRAINT "group_msg" FOREIGN KEY ("group_id") REFERENCES "groups" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "users" ADD CONSTRAINT "pfp_link" FOREIGN KEY ("pfp") REFERENCES "objects" ("id") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

CREATE OR REPLACE FUNCTION dm_cleanup() RETURNS trigger AS $$
DECLARE
BEGIN
    IF NEW.user_a IS NULL AND NEW.user_b IS NULL THEN
	DELETE FROM groups WHERE groups.id = NEW.group_id;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_check_dm_state
BEFORE UPDATE OR INSERT ON dms
FOR EACH ROW EXECUTE FUNCTION dm_cleanup();
